{{- if .Values.osba.azure.enabled }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: {{ template "tpostgresql.fullname" . }}-postgresql-azure-binding
  labels:
    app: {{ template "tpostgresql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  instanceRef:
    name: {{ template "tpostgresql.fullname" . }}-postgres-azure-instance
  secretName: {{ template "tpostgresql.osba.secret" . }}
{{- end }}
