{{- if or .Values.postgresqlembedded.enabled .Values.osba.enabled}}
##job to delete the master secret created by embedded job or osba job cause it is not part of the helm release.
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-delete-postgresql-master-secret-job
  labels:
{{ include "tpostgresql.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"    
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed,before-hook-creation" 
spec:
  template:
    spec:
      serviceAccountName: {{ template "tpostgresql.serviceAccoundName" . }}    
      containers:
      - name: {{ .Release.Name }}-delete-postgresql-master-secret-job
        image: dtzar/helm-kubectl:2.8.0
        command: ["sh", "-c", "kubectl delete secret $SECRET_NAME --namespace $SECRET_NAMESPACE"]
        env:
          - name: SECRET_NAME
            value: {{ include "tpostgresql.master.secret" . }}
          - name: SECRET_NAMESPACE
            value: {{ .Release.Namespace }}
      restartPolicy: Never            
  backoffLimit: 0    
{{- end }}
      