 {{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
{{ include "tpostgresql.labels" . | indent 4 }}
  name: {{ include "tpostgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  # Allow Dashboard to create 'postgresql-final' secret.
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - delete
{{- end -}}
