 {{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "tpostgresql.labels" . | indent 4 }}
  name: {{ include "tpostgresql.serviceAccoundName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
