{{- if .Values.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tpostgresql.master.secret" . }}
  labels:
{{ include "tpostgresql.labels" . | indent 4 }}
type: Opaque
data:
  postgresql.host: {{ default .Values.external.host | default "" | b64enc | quote }}
  postgresql.user: {{ default .Values.external.user | default "" | b64enc | quote }}
  postgresql.password: {{ default .Values.external.password | default "" | b64enc | quote }}
  postgresql.port: {{ default .Values.external.port | default "" | b64enc | quote }}
  ##The following shall not be part of the master secfret cause each app shall create it's own DB 
  postgresql.database: {{ default .Values.external.database | default "" | b64enc | quote }}
{{- end }}